(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py'
p5
sS'code'
p6
S'<code object <module> at 0xae7711d0, file "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 3>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/topf/Web2Py/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 63, in <module>\n  File "/home/topf/Web2Py/web2py/gluon/globals.py", line 409, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/topf/Web2Py/web2py/applications/Asylum/controllers/asylum.py", line 23, in show_pbase\n    buttons=[\'submit msw\'])\n  File "/home/topf/Web2Py/web2py/gluon/sqlhtml.py", line 1241, in __init__\n    (ignore_rw or f.writable or f.readable) and\n  File "/home/topf/Web2Py/web2py/gluon/packages/dal/pydal/objects.py", line 99, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.